name: healora
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/healora_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null
