name: healora
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.1.0
  cloud_firestore: ^6.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  dots_indicator: ^4.0.1
  easy_localization: ^3.0.8
  firebase_auth: ^6.1.1
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^9.0.0
  get_it: ^8.2.0
  google_fonts: ^6.3.2
  google_generative_ai: ^0.4.7
  json_annotation: ^4.9.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/healora_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null
